### ISSUE TITLE
Idea: transitive closure tables for tree structures

### ISSUE THREAD

**Issue by mhalle** [simonw/sqlite-utils#171]
I just read that sqlite has a transitive closure table extension using a virtual table in order to represent trees:

https://charlesleifer.com/blog/querying-tree-structures-in-sqlite-using-python-and-the-transitive-closure-extension/

Even without this extension, though, a util to build a transitive closure table would allow trees to be queried easily. Since it relies on self-referential foreign keys, the relationships might even be able to be automatically detected.

**Comment by simonw** [comment]
I made the `--load-extension` command much more widely supported in #137 - which should be useful for anyone who wants to use this extension.

It's a bit too obscure for me to want to add direct Python library support relating to that extension though.

**Comment by mhalle** [comment]
Thanks. As I said, I think the result (being able to query tree structures like ancestors and descendants) is more important than the implementation, and I agree that this particular sqlite extension is too obscure. Just providing an sqlite utility to build or rebuild a transitive closure table might be more generically useful. I find that hierarchical data shows up pretty frequently in some data science problems.
