### ISSUE TITLE
Progress bar for sqlite-utils insert

### ISSUE THREAD

**Issue by simonw** [simonw/sqlite-utils#173]
It would be nice if `sqlite-utils insert` had a progress bar, for when it's churning through huge CSV files.

**Comment by simonw** [comment]
This can only work when it's reading from a file, not when it's reading from standard input.

**Comment by simonw** [comment]
I know how to build this for CSV and TSV - I can read them via a file wrapper that counts how many bytes it has seen.

Not sure how to do it for JSON though. Maybe I could provide it just for newline-delimited JSON? Again I can measure progress based on how many bytes have been read.

**Comment by simonw** [comment]
I'm using a `click.File()` at the moment: https://github.com/simonw/sqlite-utils/blob/5a63b9e88c5887432eb1d7df39f304ea55038437/sqlite_utils/cli.py#L496

I'll need to change that to be something that I can easily measure progress through. Also I should change its name - `json_file` is a bad name when it sometimes handles `csv` or `tsv` instead.

**Comment by simonw** [comment]
Relevant code: https://github.com/simonw/sqlite-utils/blob/5a63b9e88c5887432eb1d7df39f304ea55038437/sqlite_utils/cli.py#L550-L560

Changing that to track progress through NL-JSON, CSV and TSV shouldn't be too hard.

**Comment by simonw** [comment]
I could use `ijson` to provide a progress bar for JSON arrays too. I'd prefer to keep that as an optional dependency though, since `sqlite-utils` is a library dependency for many other projects and it would be using `ijson` purely for the CLI component.

Here's how to iterate through a list of objects being read from a file:

```python
import json
parser = ijson.items(open(
    "/tmp/list.json"
), "item")
for object in parser:
   # ...
```

**Comment by Florents-Tselai** [comment]
> I know how to build this for CSV and TSV - I can read them via a file wrapper that counts how many bytes it has seen.
> 
> Not sure how to do it for JSON though. Maybe I could provide it just for newline-delimited JSON? Again I can measure progress based on how many bytes have been read.

I was thinking about this, while inserting a stream of ~40M line-delimited json docs. Wouldn't a `--total-expected` flag work ? 

That's [how tqdm does it](https://github.com/tqdm/tqdm/blob/fc69d5dcf578f7c7986fa76841a6b793f813df35/tqdm/std.py#L366)
