### ISSUE TITLE
.insert/.upsert/.insert_all/.upsert_all should add missing columns

### ISSUE THREAD

**Issue by simonw** [simonw/sqlite-utils#18]
This is a larger change, but it would be incredibly useful: if you attempt to insert or update a document with a field that does not currently exist in the underlying table, sqlite-utils should add the appropriate column for you.

**Comment by psychemedia** [comment]
I've just noticed that SQLite lets you IGNORE inserts that collide with a pre-existing key. This can be quite handy if you have a dataset that keeps changing in part, and you don't want to upsert and replace pre-existing PK rows but you do want to ignore collisions to existing PK rows.

Do `sqlite_utils` support such (cavalier!) behaviour?

**Comment by simonw** [comment]
Oh that's really interesting - yeah I think having an option to insert if missing, skip otherwise would be a good feature.
