### ISSUE TITLE
JSON column values get extraneously quoted 

### ISSUE THREAD

**Issue by mhalle** [simonw/sqlite-utils#20]
If the input to `sqlite-utils insert` includes a column that is a JSON array or object, `sqlite-utils query` will introduce an extra level of quoting on output:

```
# echo '[{"key": ["one", "two", "three"]}]' | sqlite-utils insert t.db t -

# sqlite-utils t.db 'select * from t'
[{"key": "[\"one\", \"two\", \"three\"]"}]

# sqlite3 t.db 'select * from t'
["one", "two", "three"]
```

This might require an imperfect solution, since sqlite3 doesn't have a JSON type. Perhaps fields that start with `["` or `{"` and end with `"]` or `"}` could be detected, with a flag to turn off that behavior for weird text fields (or vice versa).

**Comment by simonw** [comment]
I'm going to implement this using a new `--json-cols` option which works by detecting any string value that starts with [ or { and is valid JSON.
