### ISSUE TITLE
sqlite3.OperationalError: near "(": syntax error

### ISSUE THREAD

**Issue by kaihendry** [simonw/sqlite-utils#205]
The sqlite version is 3.22.0 2018-01-22 18:45:57 0c55d179733b46d8d0ba4d88e01a25e10677046ee3da1d5b1581e86726f2alt1
sqlite-utils, version 3.0

It fails here: https://github.com/kaihendry/aws-partners-datasette/runs/1528432635?check_suite_focus=true

I'm not sure where the problem is, since it works _fine locally_ on Archlinux system running 3.34.0 2020-12-01 16:14:00 a26b6597e3ae272231b96f9982c3bcc17ddec2f2b6eb4df06a224b91089fed5b

https://github.com/kaihendry/aws-partners-datasette/blob/main/create-summary-view.sh

Maybe I need to bump up from ubuntu-latest to ?

**Comment by kaihendry** [comment]
Bumping to ubuntu-20.04 appears to have solved my syntax error. 🤷

**Comment by simonw** [comment]
Yup, it looks like you're using a window function that was added in SQLite 3.25.0: https://www.sqlite.org/changes.html#version_3_25_0
