### ISSUE TITLE
Full text search possibly broken?

### ISSUE THREAD

**Issue by prabhur** [simonw/sqlite-utils#249]
I'm not quite sure if this is an issue with sqlite-utils or datasette.

**Background**
I was previously using sqlite-utils version < 3.6. I have a bunch of csv files that have some data scraped from a website.

```
sqlite-utils create-table mydb.db post \
    posted_date text \
    url text \
    title text \
    raw_text text \
    --not-null posted_date \
    --not-null url \
    --pk=url
```
FTS is enabled via
`sqlite-utils enable-fts ./mydb.db post title raw_text`

Data is loaded to the table via
`sqlite-utils insert ./mydb.db post ${filename} --csv`

Note that the data contains text in my language Tamil.

Loading happens just fine.
datasette serves the db file just fine. It recognizes FTS and shows the "search" box. However, none of the queries work. Whatever text I supply, it always returns 0 rows. I literally copy paste words from the row listing on the screen and paste it on the search box.

Interestingly, only thing  I can remember is switching to sqlite-utils 3.6. I had to do this because the prior version had an issue with column size.

I have attached one of the csv files that can be loaded to the table. Substitute "${filename}" with that file for the sqlite-utils insert command.
[posts_20200417-20201231.csv.zip](https://github.com/simonw/sqlite-utils/files/6176697/posts_20200417-20201231.csv.zip)

Interestingly, the FTS based search from datasette worked just fine before this version upgrade. That is, the queries returned results. I will try to downgrade just to see if the theory is correct. 

I appreciate any help here. Thanks.

**Comment by simonw** [comment]
Did you run `enable-fts` before you inserted the data?

If so you'll need to run `populate-fts` after the insert to populate the FTS index.

A better solution may be to add `--create-triggers` to the `enable-fts` command to add triggers that will automatically keep the index updated as you insert new records.

**Comment by prabhur** [comment]
> Did you run `enable-fts` before you inserted the data?
> 
> If so you'll need to run `populate-fts` after the insert to populate the FTS index.
> 
> A better solution may be to add `--create-triggers` to the `enable-fts` command to add triggers that will automatically keep the index updated as you insert new records.

Wow. Wasn't expecting a response this quick, especially during a weekend. :-) Sincerely appreciate it.
I tried the `populate-fts` and that did the trick. My bad for not consulting the docs again. I think I forgot to add that step when I automated the workflow.
Thanks for the suggestion. I'll close this issue. Have a great weekend and many many thanks for creating these suite of tools around sqlite.
