### ISSUE TITLE
inserting with --nl errors with: sqlite3.OperationalError: table <table> has no column named <column>

### ISSUE THREAD

**Issue by rathboma** [simonw/sqlite-utils#256]
I have a `jsonl` file, it is 10,000 lines long.

Inserting from the cli with `sqlite-utils insert db table file --nl --batch-size 10000` fails with this missing column error, even though I'm telling it to use the whole file in the first batch.

This seems similar to #18 and #139, but maybe it's unique to `--nl`?

**Comment by simonw** [comment]
Did you try running this with the `--alter` command-line option? That seems to work when I try it on a sample file here.

**Comment by simonw** [comment]
I decided to treat this as a usability bug: there's a workaround, which is adding `--alter` - but it's not at all obvious that you should do that. I addressed this in #259.
