### ISSUE TITLE
bool type not supported

### ISSUE THREAD

**Issue by frafra** [simonw/sqlite-utils#269]
Hi! Thank you for sharing this very nice tool :)
It would be nice to have support for more types, like `bool`: it is not possible to convert to boolean at the moment. My suggestion would be to handle it as `bool(int(value))`, like csvkit does.

**Comment by frafra** [comment]
`true` and `false` json values are cast to integer, which is not optimal.

**Comment by frafra** [comment]
`sqlite-utils transform` does not allow setting the column type to boolean:
```
Error: Invalid value for '--type': 'bool' is not one of 'INTEGER', 'TEXT', 'FLOAT', 'BLOB'.
```

**Comment by simonw** [comment]
SQLite doesn't have the concept of a boolean column, so there's not much I can do here: https://www.sqlite.org/datatype3.html#boolean_datatype
