### ISSUE TITLE
Support db as first parameter before subcommand, or as environment variable

### ISSUE THREAD

**Issue by mcint** [simonw/sqlite-utils#278]

**Comment by simonw** [comment]
I don't think it's possible to do this without breaking backwards compatibility, unfortunately.

**Comment by simonw** [comment]
A workaround could be to define a bash or zsh alias of some sort.

**Comment by mcint** [comment]
Fair. I looked into it, it looks like it could be done, but it would be _a bit ugly_. I can upload and link a gist of my exploration. **Click** can parse a first argument while still recognizing it as a sub-command keyword. From there, the program could:
1. ignore it preemptively if it matches a sub-command
2. and/or check if a (db) file exists at the path.

It would then also need to set a shared db argument variable.

Click also makes it easy to parse arguments from environment variables.  If you're amenable, I may submit a patch for only that, which would update each sub-command to check for a DB/SQLITE_UTILS_DB environment variable. The goal would be usage that looks like: `DB=./convenient.db sqlite-utils [operation] [args]`
