### ISSUE TITLE
Mypy fixes for rows_from_file()

### ISSUE THREAD

**Issue by adamchainz** [simonw/sqlite-utils#289]
Following https://github.com/simonw/sqlite-utils/issues/279#issuecomment-864328927

You had two mypy errors.

The first:

> sqlite_utils/utils.py:157: error: Argument 1 to "BufferedReader" has incompatible type "BinaryIO"; expected "RawIOBase"

Looking at the `BufferedReader` docs, it seems to expect a `RawIOBase`, and this [has been copied into typeshed](https://github.com/python/typeshed/blob/9ec2f8712480c57353cea097a65d75a2c4ec1846/stdlib/io.pyi#L100). There may be scope to change how `BufferedReader` is documented and typed upstream, but for now it wouldn't be too bad to use a `typing.cast()`:

```
# Detect the format, then call this recursively
buffered = io.BufferedReader(
    cast(io.RawIOBase, fp),  # Undocumented BufferedReader support for BinaryIO
    buffer_size=4096,
)
```

The second error seems to be flagging a legitimate bug in your code:

> sqlite_utils/utils.py:163: error: Argument 1 to "decode" of "bytes" has incompatible type "Optional[str]"; expected "str"

From your type hints, `encoding` may be `None`. In the CSV format block, you use `encoding or "utf-8-sig"` to set a default, maybe that's desirable in this case too?

**Comment by simonw** [comment]
Wow, thank you! I didn't know about `typing.cast()`.

**Comment by simonw** [comment]
Thanks @adamchainz - `mypy` now has a foothold on this project (and runs in CI).

**Comment by adamchainz** [comment]
Great!
