### ISSUE TITLE
Insert with --tsv and --no-headers give error about --nl arguments

### ISSUE THREAD

**Issue by davidscotson** [simonw/sqlite-utils#295]
Not quite sure if this is a bug, or just an assumption I made but I thought `--tsv` and `--no-headers` would work together when inserting from a file, and currently they seem not to (sqlite-utils, version 3.12, installed on Mac OS X via brew)

Instead it says:

`Error: Use just one of --nl, --csv or --tsv`

As if it has interpreted the --no-headers as --nl.

The --help does specifically say CSV:
 `--no-headers              CSV file has no header row`
 
And this heading in the documentation also only refers to CSV, but the text does mention TSV in passing, and I'd generally expect them to behave the same in most cases.
https://sqlite-utils.datasette.io/en/stable/cli.html#csv-files-without-a-header-row

**Comment by simonw** [comment]
Thanks, this was a bug.
