### ISSUE TITLE
Read lines with JSON object

### ISSUE THREAD

**Issue by qqilihq** [simonw/sqlite-utils#298]
I found this posted on HN a while ago and love it -- thank you!

As a minor improvement, it would be great to have the ability to parse a file with line-separated JSON objects. Currently the parser obviously requires an array wrapping all these objects.

**Comment by simonw** [comment]
This is a feature already! You can do this:

    sqlite-utils insert nl-demo.db mytable data.ndjson --nl

See https://sqlite-utils.datasette.io/en/stable/cli.html#inserting-newline-delimited-json

**Comment by qqilihq** [comment]
@simonw Awesome; thanks so much!
