### ISSUE TITLE
Invalid JSON output when no rows

### ISSUE THREAD

**Issue by gravis** [simonw/sqlite-utils#328]
`sqlite-utils query` generates a JSON output with the result from the query:

```json
[{...},{...}]
```
If no rows are returned by the query, I'm expecting an empty JSON array:

```json
[]
```

But actually I'm getting an empty string. To be consistent, the output should be `[]` when the request succeeds (return code == `0`).

**Comment by simonw** [comment]
Good catch, thanks.

**Comment by simonw** [comment]
The bug is in this code: https://github.com/simonw/sqlite-utils/blob/77c240df56068341561e95e4a412cbfa24dc5bc7/sqlite_utils/cli.py#L2205-L2227

**Comment by gravis** [comment]
Wow, that was fast! Thank you!
