### ISSUE TITLE
Provide function to generate hash_id from specified columns

### ISSUE THREAD

**Issue by psychemedia** [simonw/sqlite-utils#343]
Hi

I note that you define `_hash()` to create a `hash_id` from non-id column values in a table [here](https://github.com/simonw/sqlite-utils/blob/8f386a0d300d1b1c76132bb75972b755049fb742/sqlite_utils/db.py#L2996).

It would be useful to be able to call a complementary function to generate a corresponding `_id` from a subset of specified columns when adding items to another table, eg to support the creation of foreign keys.

Or is there a better pattern for doing that?

**Comment by simonw** [comment]
Just found myself needing this capability myself!

Relevant code:

https://github.com/simonw/sqlite-utils/blob/8f386a0d300d1b1c76132bb75972b755049fb742/sqlite_utils/db.py#L2297-L2307

https://github.com/simonw/sqlite-utils/blob/8f386a0d300d1b1c76132bb75972b755049fb742/sqlite_utils/db.py#L2996-L3001

So various functions could grow a `hash_id_columns=("title", "date")` argument which causes just those columns to be included in the hash.

Bonus: if you use `hash_id_columns=...` without setting `hash_id="id"` it could assume that you want the column to be called `id`.

**Comment by simonw** [comment]
I'm going to make that `_hash()` utility function a documented, non-underscore-prefixed function too.

**Comment by simonw** [comment]
Oops, broke mypy:

```
sqlite_utils/db.py:2600: error: Incompatible default for argument "hash_id_columns" (default has type "Default", argument has type "Optional[Iterable[str]]")
Found 1 error in 1 file (checked 49 source files)
```

**Comment by simonw** [comment]
Updated documentation: https://sqlite-utils.datasette.io/en/latest/python-api.html#setting-an-id-based-on-the-hash-of-the-row-contents

Documentation for the renamed `utils.hash_record()` function: https://sqlite-utils.datasette.io/en/latest/reference.html#sqlite-utils-utils-hash-record
