### ISSUE TITLE
Support STRICT tables

### ISSUE THREAD

**Issue by simonw** [simonw/sqlite-utils#344]
New in SQLite 3.37.0, released a few days ago: https://www.sqlite.org/stricttables.html

**Comment by simonw** [comment]
From that page:

> If you try to open a database containing the STRICT keyword in an earlier version of SQLite, it will not recognize the keyword and will report an error (except as noted below.
>
> [...]
>
> Because of a quirk in the SQL language parser, versions of SQLite prior to 3.37.0 can still read and write STRICT tables if they set "PRAGMA writable_schema=ON" immediately after opening the database file, prior to doing anything else that requires knowing the schema.

**Comment by simonw** [comment]
I'm going to build my own `pysqlite3` wheel with the latest SQLite to try this out.

**Comment by simonw** [comment]
This worked:
```
cd /tmp
mkdir sqlite-3.37
cd sqlite-3.37
wget 'https://www.sqlite.org/2021/sqlite-amalgamation-3370000.zip'
unzip sqlite-amalgamation-3370000.zip
git clone https://github.com/coleifer/pysqlite3/
cp sqlite-amalgamation-3370000/sqlite3.[ch] pysqlite3
cd pysqlite3
python3 setup.py build_static build bdist_wheel
```
This gave me a file here:

```
pysqlite3 % ls -l dist  
total 1872
-rw-r--r--  1 simon  wheel  956557 Nov 29 12:38 pysqlite3-0.4.6-cp39-cp39-macosx_10_15_x86_64.whl
```
That wheel only works when installed for Python 3.9 (it failed to install in a Python 3.10 virtual environment) - but `pip install /tmp/sqlite-3.37/pysqlite3/dist/pysqlite3-0.4.6-cp39-cp39-macosx_10_15_x86_64.whl` gave me a working `pysqlite3` - and the following worked:

```pycon
>>> import pysqlite3
>>> pysqlite3.connect(":memory:").execute("select sqlite_version()").fetchall()
[('3.37.0',)]
```

**Comment by simonw** [comment]
There are a few places that the `strict=True` option could go:

- `table.create()` and `table.create_table_sql()`
- The `Database()` constructor, to turn it on for all created tables
- The `.insert()` / `.insert_all()` etc family of methods that can implicitly create tables

I'll definitely implement the first one, and likely the second one too. I'm on the fence with regards to the third one.

**Comment by simonw** [comment]
What should happen if you attempt to use `strict=True` against a SQLite version prior to 3.37.0?

An obvious error would be best... but how about silently ignoring it on older versions instead? That would match how we handle `deterministic=True` for registering functions:

https://github.com/simonw/sqlite-utils/blob/126703706ea153f63e6134ad14e5712e4bbcb8ae/sqlite_utils/db.py#L372-L380

https://github.com/simonw/sqlite-utils/blob/93c7fd9868fed3193a1732b39bfac539e5812b0b/tests/test_register_function.py#L34-L37

**Comment by simonw** [comment]
I'm leaning towards silently ignore if SQLite version doesn't support it. That means that the first time you attempt to use `strict=True` we will need to run a test against the database connection to see what version of SQLite it uses, then cache the result to avoid making the same call again for the same connection.

**Comment by simonw** [comment]
Is there a need for an introspection function for telling if a SQLite table is in strict mode or not? How would that work?

**Comment by simonw** [comment]
From the STRICT docs:

> The SQLite parser accepts a comma-separated list of table options after the final close parenthesis in a CREATE TABLE statement. As of this writing (2021-08-23) only two options are recognized:
> 
> -   STRICT
> -   [WITHOUT ROWID](https://www.sqlite.org/withoutrowid.html)

So I think I need to read the `CREATE TABLE` statement from the `sqlite_master` table, split on the last `)`, split those tokens on `,` and see if `create` is in there (case insensitive).

**Comment by simonw** [comment]
Made myself a test strict table like so:

```pycon
>>> import pysqlite3
>>> conn = pysqlite3.connect("/tmp/strict-table.db")
>>> conn.execute("create table foo (id integer primary key, name text, weight real) strict")
<pysqlite3.dbapi2.Cursor object at 0x104317340>
>>> conn.execute("insert into foo (name, weight) values ('Lila', '2.31')")
<pysqlite3.dbapi2.Cursor object at 0x104317730>
```
Uploaded that to: https://static.simonwillison.net/static/2021/strict-table.db

**Comment by simonw** [comment]
Here's a function that detects if `strict` is supported or not:
```python
import secrets
import sqlite3

def supports_strict_tables(db = None):
    if db is None:
        db = sqlite3.connect(":memory:")
    try:
        table_name = 't{}'.format(secrets.token_hex(16))
        with db:
            db.execute("create table {} (name text) strict".format(table_name))
            db.execute("drop table {}".format(table_name))
        return True
    except:
        return False
```

**Comment by simonw** [comment]
I'm going to add that as `db.supports_strict`.

**Comment by simonw** [comment]
I haven't documented `db.supports_strict` yet (I documented `table.strict`) because there wasn't an obvious section of the documentation for it.

I need to remember to document it once I add documentation for the `strict=True` parameter.

**Comment by simonw** [comment]
Need to figure out a good pattern for testing this in CI too - it will currently skip the new tests if it doesn't have SQLite 3.37 or higher.

**Comment by tkhattra** [comment]
hello Simon,

I've added more STRICT table support per https://github.com/simonw/sqlite-utils/issues/344#issuecomment-982014776 in changeset https://github.com/simonw/sqlite-utils/commit/e4b9b582cdb4e48430865f8739f341bc8017c1e4.
It also fixes table.transform() to preserve STRICT mode.
Please pull if you deem appropriate. Thanks!
