### ISSUE TITLE
Command for creating an empty database

### ISSUE THREAD

**Issue by simonw** [simonw/sqlite-utils#348]
I sometimes find the need to create an empty SQLite database file - for example if I want to enable WAL on it before using it with another script. I currently do that like this:

    sqlite3 my.db vacuum
    sqlite-utils enable-wal my.db

It would be nice if `sqlite-utils` had a convenience command for doing this.

**Comment by simonw** [comment]
Maybe this:

    sqlite-utils create-database my.db

With options that include `--enable-wal`.

This is consistent with the existing `create-table` and `create-view` commands.

**Comment by simonw** [comment]
Potential other options could include:

- `--page-size` https://www.sqlite.org/pragma.html#pragma_page_size

**Comment by eyeseast** [comment]
I'd use this. Right now, I tend to do `touch my.db` and then `enable-wal` or whatever else, but I'm never sure if that's a bad idea.

**Comment by simonw** [comment]
I'm not going to implement `--page-size` unless someone specifically requests it - I don't like having features that I've never needed to use myself.

**Comment by simonw** [comment]
Documentation: https://sqlite-utils.datasette.io/en/latest/cli.html#creating-an-empty-database

**Comment by simonw** [comment]
Wrote a lot more about this feature here: https://simonwillison.net/2022/Jan/12/how-i-build-a-feature/
