### ISSUE TITLE
Support IF NOT EXISTS for table creation

### ISSUE THREAD

**Issue by rafguns** [simonw/sqlite-utils#397]
Currently, I have a bunch of code that looks like this:

```python
subjects = db["subjects"] if db["subjects"].exists() else db["subjects"].create({
    ...
})
```
It would be neat if sqlite-utils could simplify that by supporting `CREATE TABLE IF NOT EXISTS`, so that I'd be able to write, e.g.

```python
subjects = db["subjects"].create({...}, if_not_exists=True)
```

**Comment by simonw** [comment]
This is a good idea. We already have that parameter for the `table.create_index()` method: https://sqlite-utils.datasette.io/en/stable/reference.html#sqlite_utils.db.Table.create_index

**Comment by simonw** [comment]
Just noticed there's no explicit test coverage for the `db["table"].create(...)` method.

**Comment by simonw** [comment]
Updated documentation is here: https://sqlite-utils.datasette.io/en/latest/python-api.html#explicitly-creating-a-table
