### ISSUE TITLE
Document how to add a primary key to a rowid table using `sqlite-utils transform --pk`

### ISSUE THREAD

**Issue by fgregg** [simonw/sqlite-utils#403]
sometimes we have tables that don't have primary keys, but ought to have them. we *can* use rowid for that, but it would often be nicer to have an explicit primary key. using the current value of rowid would be fine.

**Comment by fgregg** [comment]
you can hack something like this:

`sqlite-utils convert my_database my_table rowid "{'id': value}" --multi`

**Comment by simonw** [comment]
This is already possible using `sqlite-utils transform` like so:

```
% echo '[{"name": "Barry"}, {"name": "Sandra"}]' | sqlite-utils insert rowid.db records -
% sqlite-utils schema rowid.db                                                           
CREATE TABLE [records] (
   [name] TEXT
);
% sqlite-utils rows rowid.db records
[{"name": "Barry"},
 {"name": "Sandra"}]
% sqlite-utils transform rowid.db records --pk id
% sqlite-utils rows rowid.db records
[{"id": 1, "name": "Barry"},
 {"id": 2, "name": "Sandra"}]
% sqlite-utils schema rowid.db
CREATE TABLE "records" (
   [id] INTEGER PRIMARY KEY,
   [name] TEXT
);
% echo '[{"name": "Barry 2"}, {"name": "Sandra 2"}]' | sqlite-utils insert rowid.db records -
% sqlite-utils rows rowid.db records                                                         
[{"id": 1, "name": "Barry"},
 {"id": 2, "name": "Sandra"},
 {"id": 3, "name": "Barry 2"},
 {"id": 4, "name": "Sandra 2"}]
```
It's not covered in the documentation though: https://sqlite-utils.datasette.io/en/stable/cli.html#transforming-tables

**Comment by simonw** [comment]
New documentation: https://sqlite-utils.datasette.io/en/latest/cli.html#adding-a-primary-key-to-a-rowid-table

**Comment by fgregg** [comment]
dddoooope
