### ISSUE TITLE
Document how to use a `--convert` function that runs initialization code first

### ISSUE THREAD

**Issue by strada** [simonw/sqlite-utils#420]
When I have an insert command with transform like this:

```
cat items.json | jq '.data' | sqlite-utils insert listings.db listings - --convert '
d = enchant.Dict("en_US")
row["is_dictionary_word"] = d.check(row["name"])
'  --import=enchant --ignore
```

I noticed as the number of rows increases the operation becomes quite slow, likely due to the creation of the `d = enchant.Dict("en_US")` object for each row. Is there a way to share that instance `d` between transform function calls, like a shared context?

**Comment by simonw** [comment]
I can think of three ways forward:

- Figure out a pattern that gets that local file import workaround to work
- Add another option such as `--convert-init` that lets you pass code that will be executed once at the start
- Come up with a pattern where the `--convert` code can run some initialization code and then return a function which will be called against each value

I quite like the idea of that third option - I'm going to prototype it and see if I can work something out.

**Comment by simonw** [comment]
Here's how the `_compile_code()` mechanism works at the moment: https://github.com/simonw/sqlite-utils/blob/396f80fcc60da8dd844577114f7920830a2e5403/sqlite_utils/utils.py#L308-L342

At the end it does this:
```python
    return locals["fn"]
```
So it's already building and then returning a function.

The question is if there's a sensible way to allow people to further customize that function by executing some code first, in a way that's easy to explain.

**Comment by simonw** [comment]
Aha! This may be possible already: https://github.com/simonw/sqlite-utils/blob/396f80fcc60da8dd844577114f7920830a2e5403/sqlite_utils/utils.py#L311-L316

And yes, this does indeed work - you can do something like this:

```
echo '{"name": "harry"}' | sqlite-utils insert db.db people - --convert '
import time
# Simulate something expensive
time.sleep(1)

def convert(row):
    row["upper"] = row["name"].upper()
'
```
So this is a documentation issue - there's a trick for it but I didn't know what the trick was!

**Comment by simonw** [comment]
That documentation is split across a few places. This is the only bit that talks about `def convert()` pattern right now:

- https://sqlite-utils.datasette.io/en/stable/cli.html#converting-data-in-columns

But that's for `sqlite-utils convert` - the documentation for `sqlite-utils insert --convert` at https://sqlite-utils.datasette.io/en/stable/cli.html#applying-conversions-while-inserting-data doesn't mention it.

Since both `sqlite-utils convert` and `sqlite-utils insert --convert` apply the same rules to the code, they should link to a shared explanation in the documentation.

**Comment by simonw** [comment]
Actually this doesn't work as I thought. This demo shows that the initialization code is run once per item, not a single time at the start of the run:
```
% sqlite-utils insert dogs.db dogs dogs.json --convert '
import random
print("seeding")
random.seed(10)
print(random.random())

def convert(row):
    print(row)
    row["random_score"] = random.random()
'
seeding
0.5714025946899135
seeding
0.5714025946899135
seeding
0.5714025946899135
seeding
0.5714025946899135
```
Also that `print(row)` line is not being printed anywhere that gets to the console for some reason.

**Comment by simonw** [comment]
This works:
```
sqlite-utils insert dogs.db dogs dogs.json --convert '
import random
print("seeding")
random.seed(10)
print(random.random())

def convert(row):
    global random
    print(row)
    row["random_score"] = random.random()
'
```
Having to use `global random` inside the function is frustrating but apparently necessary. https://stackoverflow.com/a/56552138/6083

**Comment by simonw** [comment]
Now documented here: https://sqlite-utils.datasette.io/en/latest/cli.html#using-a-convert-function-to-execute-initialization

**Comment by simonw** [comment]
So now this should solve your problem:
```
cat items.json | jq '.data' | sqlite-utils insert listings.db listings - --convert '
d = enchant.Dict("en_US")

def convert(row):
    global d
    row["is_dictionary_word"] = d.check(row["name"])
'  --import=enchant --ignore
```

**Comment by simonw** [comment]
Wrote about this in my weeknotes: https://simonwillison.net/2022/Mar/28/datasette-auth0/#new-features-as-documentation

**Comment by strada** [comment]
@simonw Thanks for looking into it and documenting the solution!

**Comment by simonw** [comment]
I found a fix that makes that `global` heavy workaround unnecessary:

- #472
