### ISSUE TITLE
`sqlite3.NotSupportedError`: deterministic=True requires SQLite 3.8.3 or higher

### ISSUE THREAD

**Issue by simonw** [simonw/sqlite-utils#425]
Got this error while investigating:
- #421

Even though I was using the `LD_PRELOAD` trick from https://til.simonwillison.net/sqlite/ld-preload to use a newer version of SQLite.

_Originally posted by @simonw in https://github.com/simonw/sqlite-utils/issues/421#issuecomment-1098531354_

**Comment by simonw** [comment]
I figured out a workaround in https://github.com/simonw/sqlite-utils/issues/421#issuecomment-1098535531

The current `register(fn)` method looks like this: https://github.com/simonw/sqlite-utils/blob/95522ad919f96eb6cc8cd3cd30389b534680c717/sqlite_utils/db.py#L389-L403

This alternative implementation worked in the environment where that failed:

```python
        def register(fn):
            name = fn.__name__
            arity = len(inspect.signature(fn).parameters)
            if not replace and (name, arity) in self._registered_functions:
                return fn
            kwargs = {}
            done = False
            if deterministic:
                # Try this, but fall back if sqlite3.NotSupportedError
                try:
                    self.conn.create_function(name, arity, fn, **dict(kwargs, deterministic=True))
                    done = True
                except sqlite3.NotSupportedError:
                    pass
            if not done:
                self.conn.create_function(name, arity, fn, **kwargs)
            self._registered_functions.add((name, arity))
            return fn
```

**Comment by simonw** [comment]
That broke Python 3.7 because it doesn't support `deterministic=True` even being passed:

> function takes at most 3 arguments (4 given)

**Comment by simonw** [comment]
Releated:
- #408

**Comment by McEazy2700** [comment]
Hi, I'm trying to deploy my site using elasticbeanstalk and I keep getting this same error :
deterministic=True requires SQLite 3.8.3 or higher

I saw your previous solution that involves editing sqlite-utils/sqlite_utils/db.py file, but I'm curious as to how that will work in production.

**Comment by Dhyanesh97** [comment]
is this change released ? Because when we run docker containers issue still persists for production deployments.
