### ISSUE TITLE
CSV files with too many values in a row cause errors

### ISSUE THREAD

**Issue by frafra** [simonw/sqlite-utils#440]
*Original title: csv.DictReader can have None as key*

In some cases, `csv.DictReader` can have `None` as key for unnamed columns, and a list of values as value.
`sqlite_utils.utils.rows_from_file` cannot handle that:

```python
url="https://artsdatabanken.no/Fab2018/api/export/csv"
db = sqlite_utils.Database(":memory")

with urlopen(url) as fab:
    reader, _ = sqlite_utils.utils.rows_from_file(fab, encoding="utf-16le")   
    db["fab2018"].insert_all(reader, pk="Id")
```

Result:
```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/user/.local/pipx/venvs/sqlite-utils/lib/python3.8/site-packages/sqlite_utils/db.py", line 2924, in insert_all
    chunk = list(chunk)
  File "/home/user/.local/pipx/venvs/sqlite-utils/lib/python3.8/site-packages/sqlite_utils/db.py", line 3454, in fix_square_braces
    if any("[" in key or "]" in key for key in record.keys()):
  File "/home/user/.local/pipx/venvs/sqlite-utils/lib/python3.8/site-packages/sqlite_utils/db.py", line 3454, in <genexpr>
    if any("[" in key or "]" in key for key in record.keys()):
TypeError: argument of type 'NoneType' is not iterable
```

Code:
https://github.com/simonw/sqlite-utils/blob/59be60c471fd7a2c4be7f75e8911163e618ff5ca/sqlite_utils/db.py#L3454

`sqlite-utils insert` from command line is not affected by this issue.

**Comment by simonw** [comment]
Steps to demonstrate that `sqlite-utils insert` is not affected:

```bash
curl -o artsdatabanken.csv https://artsdatabanken.no/Fab2018/api/export/csv
sqlite-utils insert arts.db artsdatabanken artsdatabanken.csv --sniff --csv --encoding utf-16le
```

**Comment by simonw** [comment]
I don't understand why that works but calling `insert_all()` does not.

**Comment by simonw** [comment]
Here are full steps to replicate the bug:
```python
from urllib.request import urlopen
import sqlite_utils
with urlopen("https://artsdatabanken.no/Fab2018/api/export/csv") as fab:
    reader, other = sqlite_utils.utils.rows_from_file(fab, encoding="utf-16le")
    db["fab2018"].insert_all(reader, pk="Id")
```

**Comment by simonw** [comment]
Aha! I think I see what's happening here. Here's what `DictReader` does if one of the lines has too many items in it:

```pycon
>>> import csv, io
>>> list(csv.DictReader(io.StringIO("id,name\n1,Cleo,nohead\n2,Barry")))
[{'id': '1', 'name': 'Cleo', None: ['nohead']}, {'id': '2', 'name': 'Barry'}]
```
See how that row with too many items gets this:
`[{'id': '1', 'name': 'Cleo', None: ['nohead']}`

That's a `None` for the key and (weirdly) a list containing the single item for the value!

**Comment by simonw** [comment]
That weird behaviour is documented here: https://docs.python.org/3/library/csv.html#csv.DictReader

> If a row has more fields than fieldnames, the remaining data is put in a list and stored with the fieldname specified by *restkey* (which defaults to `None`). If a non-blank row has fewer fields than fieldnames, the missing values are filled-in with the value of *restval* (which defaults to `None`).

**Comment by simonw** [comment]
So I need to make a design decision here: what should `sqlite-utils` do with CSV files that have rows with more values than there are headings?

Some options:

- Ignore those extra fields entirely - silently drop that data. I'm not keen on this.
- Throw an error. The library does this already, but the error is incomprehensible - it could turn into a useful, human-readable error instead.
- Put the data in a JSON list in a column with a known name (`None` is not a valid column name, so not that). This could be something like `_restkey` or `_values_with_no_heading`. This feels like a better option, but I'd need to carefully pick a name for it - and come up with an answer for the question of what to do if the CSV file being important already uses that heading name for something else.

**Comment by simonw** [comment]
Whatever I decide, I can implement it in `rows_from_file()`, maybe as an optional parameter - then decide how to call it from the `sqlite-utils insert` CLI (perhaps with a new option there too).

**Comment by simonw** [comment]
Here's the current function signature for `rows_from_file()`:

https://github.com/simonw/sqlite-utils/blob/26e6d2622c57460a24ffdd0128bbaac051d51a5f/sqlite_utils/utils.py#L174-L179

**Comment by simonw** [comment]
The exception will be called `RowError`.

**Comment by simonw** [comment]
Interesting challenge in writing tests for this: if you give `csv.Sniffer` a short example with an invalid row in it sometimes it picks the wrong delimiter!

    id,name\r\n1,Cleo,oops

It decided the delimiter there was `e`.

**Comment by simonw** [comment]
That broke `mypy`:

`sqlite_utils/utils.py:229: error: Incompatible types in assignment (expression has type "Iterable[Dict[Any, Any]]", variable has type "DictReader[str]")`

**Comment by simonw** [comment]
Getting this past `mypy` is really hard!

```
% mypy sqlite_utils
sqlite_utils/utils.py:189: error: No overload variant of "pop" of "MutableMapping" matches argument type "None"
sqlite_utils/utils.py:189: note: Possible overload variants:
sqlite_utils/utils.py:189: note:     def pop(self, key: str) -> str
sqlite_utils/utils.py:189: note:     def [_T] pop(self, key: str, default: Union[str, _T] = ...) -> Union[str, _T]
```
That's because of this line:

    row.pop(key=None)

Which is legit here - we have a dictionary where one of the keys is `None` and we want to remove that key. But the baked in type is apparently `def pop(self, key: str) -> str`.

**Comment by simonw** [comment]
Filed an issue against `python/typeshed`:

- https://github.com/python/typeshed/issues/8075

**Comment by simonw** [comment]
I'm going to rename `restkey` to `extras_key` for consistency with `ignore_extras`.

**Comment by simonw** [comment]
Documentation: https://sqlite-utils.datasette.io/en/latest/python-api.html#reading-rows-from-a-file
