### ISSUE TITLE
Conda Forge

### ISSUE THREAD

**Issue by thewchan** [simonw/sqlite-utils#477]
Hello! I have successfully put this package on to Conda Forge, and I have extending the invitation for the owner/maintainers of this package to be maintainers on Conda Forge as well. Let me know if you are interested! Thanks.
https://github.com/conda-forge/sqlite-utils-feedstock

**Comment by simonw** [comment]
Hi @thewchan - thanks for that! Yes I'm interested, can you invite `swillison` @ Google's email provider please?

**Comment by thewchan** [comment]
Will do!
