### ISSUE TITLE
balanced table default column_order

### ISSUE THREAD

**Issue by chapmanjacobd** [simonw/sqlite-utils#482]
Is there any performance or size difference with column order in SQLITE ? similar to this https://www.cybertec-postgresql.com/en/column-order-in-postgresql-does-matter/

It might be interesting to have an option to create with an optimized column order. I'm assuming this would look something like INTEGER columns, REAL columns, BLOB columns, TEXT columns, NULL columns. NULL columns at the end because they are more likely to be TEXT and it is impossible to know if they will become INTEGER

(Of course, any schema evolution would reduce optimization but maybe column order could also be re-evaluated when schema changes)

**Comment by simonw** [comment]
This is an interesting research area! Running the same experiment as the one in https://www.cybertec-postgresql.com/en/column-order-in-postgresql-does-matter/ could demonstrate one way or another if column ordering makes a difference with regards to performance or not.

My hunch is that even if it does this wouldn't be a feature to bake into `sqlite-utils` itself, beyond the existing features for changing the order of columns in a table (https://sqlite-utils.datasette.io/en/stable/python-api.html#changing-column-order).
