### ISSUE TITLE
Progressbar not shown when inserting/upserting jsonlines file

### ISSUE THREAD

**Issue by MischaU8** [simonw/sqlite-utils#485]
When inserting or upserting a jsonlines file, no progressbar is shown. Expected behavior is that, just like with .csv/.tsv files, also for a jsonlines file (--nl), unless --silent is provided, a progressbar is shown.

```bash
sql-utils upsert mydb.db posts posts.jl --nl --pk post_id
(silence)
```

Currently `file_progress` is only called within the tsv/csv logic, however I think it can be safely wrapped around all the all the input formats that use `decoded`: https://github.com/simonw/sqlite-utils/blob/main/sqlite_utils/cli.py#L963

**Comment by simonw** [comment]
A note from PR #486: https://github.com/simonw/sqlite-utils/issues/486#issuecomment-1248591268_

> ```
> sqlite-utils insert /tmp/t3.db t /tmp/big.json 
>   [####################################]  100%
> ```
> This is actually not doing the right thing. The problem is that `sqlite-utils` doesn't include a streaming JSON parser, so it instead reads that entire JSON file into memory first (exhausing the progress bar to 100% instantly) and then does the rest of the work in-memory while the bar sticks at 100%.

I decided to land this anyway. If a streaming JSON parser is added later it will start to work.
