### ISSUE TITLE
Specify foreign key against compound key in other table

### ISSUE THREAD

**Issue by ryanfox** [simonw/sqlite-utils#487]
When inserting rows via the library, is it possible to specify a foreign key to a compound primary key?

For example, suppose I create a table:
```
db = Database('events.db')
db['events'].insert_all([
    {'venue': 'Times Square', 'date': '2022-12-31', 'title': 'Rockin New Year Eve'},
    {'venue': 'Wembley Stadium', 'date': '2022-06-05', 'title': 'FA Cup'},
    {'venue': 'Times Square', 'date': '2021-12-31', 'title': 'Rockin New Year Eve'},
], pk=('date', 'venue'))
```

And I want to add related data in another table:
```
act = {'name': 'Rick Astley', 'venue': 'Times Square', 'date': '2021-12-31' }
db['performers'].insert(act, pk=<???>)
```

Is it possible to specify a value for `pk` that will point to the compound primary key in `events`?

SQLite does support it:
https://www.sqlite.org/foreignkeys.html#fk_composite

**Comment by simonw** [comment]
This isn't supported yet - there's an older issue for that here:

- #117

**Comment by ryanfox** [comment]
Perfect. Apologies, I searched but didn’t see that one for some reason.
Thank you.
