### ISSUE TITLE
Show more information when JSON can't be imported with sqlite-utils insert

### ISSUE THREAD

**Issue by voltagex** [simonw/sqlite-utils#532]
I am currently trying to import the [JSON export of my data from Discord](https://support.discord.com/hc/en-us/articles/360004027692-Requesting-a-Copy-of-your-Data), specifically `activity/reporting/events-*.json`

```
sqlite-utils.exe insert test.db reporting events-2023-00000-of-00001.json
  [###################################-]   99%  00:00:00
Error: Invalid JSON - use --csv for CSV or --tsv for TSV files
```

Please show more information as to *why* this is invalid, if possible.

I am using version 3.30 with Python 3.10 on Windows 11.

**Comment by simonw** [comment]
Was this a newline-delimited JSON file perhaps?

**Comment by simonw** [comment]
```
% sqlite-utils insert /tmp/b.db blah /tmp/blah.txt
  [####################################]  100%
Error: Invalid JSON - use --csv for CSV or --tsv for TSV files

JSON error: Expecting value: line 1 column 1 (char 0)
```
