### ISSUE TITLE
Ability to list views, and to access db["view_name"].rows / rows_where / etc

### ISSUE THREAD

**Issue by ftrain** [simonw/sqlite-utils#54]
The docs show me how to create a view via `db.create_view()` but I can't seem to get back to that view post-creation; if I query it as a table it returns `None`, and it doesn't appear in the table listing, even though querying the view works fine from inside the sqlite3 command-line.

It'd be great to have the view as a pseudo-table, or if the python/sqlite3 module makes that hard to pull off (I couldn't figure it out), to have that edge-case documented next to the `db.create_view()` docs.

**Comment by simonw** [comment]
Good catch: `create_view()` is an earlier utility method from before I started adding methods like `db["table"].rows` and `.rows_where()`.

**Comment by simonw** [comment]
Closed by #55

**Comment by simonw** [comment]
Documentation is here: https://sqlite-utils.readthedocs.io/en/latest/python-api.html#listing-views

**Comment by simonw** [comment]
Released in 1.10: https://sqlite-utils.readthedocs.io/en/stable/changelog.html#v1-10

**Comment by ftrain** [comment]
Extremely cool and easy to understand. Thank you!
