### ISSUE TITLE
Plugin system

### ISSUE THREAD

**Issue by asg017** [simonw/sqlite-utils#567]
I'd like there to be a plugin system for sqlite-utils, similar to the datasette/llm plugins. I'd like to make plugins that would do things like:

- Register SQLite extensions for more SQL functions + virtual tables
- Register new subcommands
- Different input file formats for `sqlite-utils memory`
- Different output file formats (in addition to `--csv` `--tsv` `--nl` etc.

A few real-world use-cases of plugins I'd like to see in sqlite-utils:

- Register many of my sqlite extensions in sqlite-utils (`sqlite-http`, `sqlite-lines`, `sqlite-regex`, etc.)
- New subcommands to work with `sqlite-vss` vector tables
- Input/ouput Parquet/Avro/Arrow IPC files with `sqlite-arrow`

**Comment by asg017** [comment]
Another use-case: I want to make a `sqlite-utils` plugin that'll help me insert data into Datasette. 

```bash
sqlite-utils insert-datasette \
  --token $DATASETTE_API_KEY \
  https://latest.datasette.io/fixtures/my-table \
  'select ...'
```


This could also be a datasette plugin (ex `datasette upload-data ...`, but you can also think of `sqlite-utils` plugins that upload to S3, a postgres table, other DBMS's, etc.)

**Comment by simonw** [comment]
I really like this. I'm also interested in:
- Plugins that make new custom SQL functions available - similar to this Datasette hook: https://docs.datasette.io/en/stable/plugin_hooks.html#prepare-connection-conn-database-datasette
- Plugins that register functions that can be used as recipes for `sqlite-utils convert` https://sqlite-utils.datasette.io/en/stable/cli.html#sqlite-utils-convert-recipes

The upload-data-to-Datasette problem is planned to be solved by a future version of https://github.com/simonw/dclient

**Comment by redraw** [comment]
Before writing [sqlite-ner](https://github.com/redraw/sqlite-ner), I was wondering if `sqlite-utils` had a plugin system, that would be nice

**Comment by eyeseast** [comment]
Would this possibly make a bunch of `x-to-sqlite` tools obsolete? Or nudge some to become plugins?

**Comment by simonw** [comment]
> Would this possibly make a bunch of `x-to-sqlite` tools obsolete? Or nudge some to become plugins?

Yeah, it could do! That's not a terrible idea to be honest, those things have really been proliferating.

Alternatively, they could each register themselves as plugins in addition - so if you install e.g. `pocket-to-sqlite` you could then optionally also run it as `sqlite-utils pocket-to-sqlite ...`

The benefit there is for people who install `sqlite-utils` from Homebrew, where it gets its own virtual environment. They could run:

```bash
brew install sqlite-utils
sqlite-utils install pocket-to-sqlite

sqlite-utils pocket-to-sqlite ...
```

**Comment by simonw** [comment]
I'm going to start by adding the `register_command` hook using the exact same pattern as Datasette and LLM.

**Comment by simonw** [comment]
Here's documentation for the new plugins mechanism, including a very short tutorial on writing a new plugin (inspired by https://llm.datasette.io/en/stable/plugins/tutorial-model-plugin.html):

https://sqlite-utils.datasette.io/en/latest/plugins.html

**Comment by eyeseast** [comment]
Cool. I might try to add a geojson plugin that handles both input and output. That would help me out a lot.

**Comment by simonw** [comment]
Splitting off an issue for `prepare_connection()` since Alex got the PR in seconds before I shipped 3.34!

**Comment by simonw** [comment]
Now that we have two plugin hooks I'm closing this issue (we can open other issues for further hooks).

**Comment by saeedesmaili** [comment]
While reading the plugin system docs, I was wondering if there is a page in yhe docs which provides a list of the available plugins (ones that others have already developed)?
I'm looking for using vectors and vector search with sqlite-utils, but I can't find a way, so I was hoping there is already a plugin for using sqlite-vss or sqlite-vec.

**Comment by asg017** [comment]
@saeedesmaili I'll contribute them to the `sqlite-utils` docs soon. In the meantime, you can run:

```bash
sqlite-utils install sqlite-utils-sqlite-vec
```

And `sqlite-vec` SQL functions will be loaded into future connections.
