### ISSUE TITLE
Support enabling FTS on views

### ISSUE THREAD

**Issue by amjith** [simonw/sqlite-utils#58]
Right now enable_fts() is only implemented for Table(). Technically sqlite supports enabling fts on views. But it requires deeper thought since views don't have `rowid` and the current implementation of enable_fts() relies on the presence of `rowid` column. 

It is possible to provide an alternative rowid using the `content_rowid` option to the FTS5() function. 

Ref: https://sqlite.org/fts5.html#fts5_table_creation_and_initialization

>  The "content_rowid" option, used to set the rowid field of an external content table. 

This will further complicate `enable_fts()` function by adding an extra argument. I'm wondering if that is outside the scope of this tool or should I work on that feature and send a PR?

**Comment by simonw** [comment]
I don't think this is valuable enough to justify adding to the library - especially since you can execute FTS search against views by joining to an FTS table built against an underlying table.
