### ISSUE TITLE
Feature request: enable extensions loading

### ISSUE THREAD

**Issue by aborruso** [simonw/sqlite-utils#69]
Hi, it would be great to add a parameter that enables the load of a sqlite extension you need.

Something like "-ext modspatialite".

In this way your great tool would be even more comfortable and powerful.

Thank you very much

**Comment by simonw** [comment]
This is a good idea. Datasette has this in the form of the `--load-extension` CLI argument, e.g. for SpatiaLite here: https://datasette.readthedocs.io/en/stable/spatialite.html#installation

Having that available for `sqlite-utils` definitely makes sense.

**Comment by simonw** [comment]
Did some work on this for #134 in 7e9aad7e1c09d1cf80d0b4d17d6157212a4b857d

I still need to add `--load-extension` to other CLI methods, see #137. Closing this issue in favour of that one.

**Comment by aborruso** [comment]
Great @simonw thank you very much
